### ISSUE TITLE
Unable to parse Measurement Protocol JSON payload. extraneous characters after end of JSON object

### ISSUE THREAD

**Issue by bptf-iaps** [clovett/SimpleGoogleAnalytics#4]
I went through the docs to setup the Measurement ID and API Secret: https://developers.google.com/analytics/devguides/collection/protocol/ga4/sending-events?client_type=gtag

I also got my client_id via gtag.js('get') in Google Chrome console.

Tried numerous tests, with a few passing but most giving the error mentioned in the title, which I get in the errors array:

`var errors = await HttpProtocol.ValidateMeasurements(analytics);`

Here is the code:

```
var analytics = new Analytics()
{
    MeasurementId = AppSettings.GA4_MeasurementID,
    ApiSecret = AppSettings.GA4_ApiSecret,
    ClientId = AppSettings.GA4_ClientID,
};
analytics.Events.Add(new PageMeasurement()
{
    Path = "https://www.domain.tld",
    Title = "test",
});
var errors = await HttpProtocol.ValidateMeasurements(analytics);
if (errors.ValidationMessages?.Length > 0)
{
    foreach (var error in errors.ValidationMessages)
    {
        Console.WriteLine("{0}: {1}", error.ValidationCode, error.Description);
    }
}
else
{
    Console.WriteLine("measurement validated!!");
    await HttpProtocol.PostMeasurements(analytics);
    Console.WriteLine("measurement sent!!");
}
```

**Comment by bptf-iaps** [comment]
I just noticed now that the `ValidateMeasurements` function's Post URL contains **/debug/**.  Do I forego that function when in a live environment, or should it still be used to validate prior to committing?

**Comment by bptf-iaps** [comment]
Never mind.  It works fine when not calling `ValidationMeasurements`.  I also setup an independent `Task` for this request and also added a flag to make sure it doesn't run more than once, as it seems to want to do so when called via `CarouselView`'s `CurrentItemChanged` event.  Also running that task via Dispatcher: `Dispatcher.Dispatch(async () => await GA4Tracker(data));`

**Comment by clovett** [comment]
Thanks for the bug report, I just added a new test in [Program.cs](https://github.com/clovett/SimpleGoogleAnalytics/blob/main/Test/Program.cs) for PageMeasurement and `ValidationMeasurements` worked fine for me.  Make sure you don't try and share one Analytics object, just create a new one each time you want to post, so make sure the Analytics doesn't change while HttpProtocol.Post is running.
